{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Fake_currency_det.ipynb","provenance":[],"collapsed_sections":[],"mount_file_id":"1llnEG_Hd2NkcY0w5V60PrzzzbkBOZFC3","authorship_tag":"ABX9TyMR7yJC5KPly42DhqY5PaUQ"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"S3js54Tlq7QE","executionInfo":{"status":"ok","timestamp":1625066184894,"user_tz":-330,"elapsed":582,"user":{"displayName":"counter feit","photoUrl":"","userId":"05828223437646902637"}},"outputId":"d01073e4-0868-4573-8abf-0611565260c0"},"source":["%cd /content/drive/MyDrive/"],"execution_count":1,"outputs":[{"output_type":"stream","text":["/content/drive/MyDrive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"QbyC4pSBrL_J","executionInfo":{"status":"ok","timestamp":1624634291509,"user_tz":-330,"elapsed":643,"user":{"displayName":"counter feit","photoUrl":"","userId":"05828223437646902637"}},"outputId":"0e06f289-a331-40a7-d84d-c879ffd2ee4f"},"source":["%cd fake_currency_final/"],"execution_count":null,"outputs":[{"output_type":"stream","text":["/content/drive/MyDrive/fake_currency_final\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"aq6FkZ0-rOM7","executionInfo":{"status":"ok","timestamp":1624701492380,"user_tz":-330,"elapsed":350,"user":{"displayName":"counter feit","photoUrl":"","userId":"05828223437646902637"}},"outputId":"b0dd30ce-1195-4b5c-f76c-fce372ef32b9"},"source":["!python pretrained_vgg16_train.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["python3: can't open file 'pretrained_vgg16_train.py': [Errno 2] No such file or directory\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"mxf4k2dCrpmX","executionInfo":{"status":"ok","timestamp":1624634769774,"user_tz":-330,"elapsed":3069,"user":{"displayName":"counter feit","photoUrl":"","userId":"05828223437646902637"}},"outputId":"91bb86f3-c3b6-4c61-ad63-a43f4bf6fb2d"},"source":["!python test.py"],"execution_count":null,"outputs":[{"output_type":"stream","text":["2021-06-25 09:55:38.767108: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0\n","Traceback (most recent call last):\n","  File \"test.py\", line 6, in <module>\n","    img = image.load_img(\"./content/drive/MyDrive/fake_currency_final/dataset/test/real/Real_1.jpg\",target_size=(224,224))\n","  File \"/usr/local/lib/python3.7/dist-packages/keras/preprocessing/image.py\", line 293, in load_img\n","    target_size=target_size, interpolation=interpolation)\n","  File \"/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/utils.py\", line 113, in load_img\n","    with open(path, 'rb') as f:\n","FileNotFoundError: [Errno 2] No such file or directory: './content/drive/MyDrive/fake_currency_final/dataset/test/real/Real_1.jpg'\n"],"name":"stdout"}]}]}